---
- hosts: all
  roles:
    - zuul-include-vars
    - install-repo-script
    - repo-sandbox-prepare2
    - set-zuul-log-path-fact
    - reach-jenkins-with-zuuls-tentacle
    - role: publish-windows-containers
      registries:
        - host: "10.84.5.81:5000"
          protocol: http
        - host: "index.docker.io/opencontrailnightly"
          protocol: https
