---

- name: Gather dmesg output
  command: dmesg
  register: dmesg

- name: Write host dmesg output
  delegate_to: localhost
  copy:
    content: "{{ dmesg.stdout }}"
    dest: "{{ zuul.executor.log_root }}/zuul-info/dmesg.{{ inventory_hostname }}.txt"

- name: Gather ps output
  command: "ps aux -H"
  register: ps

- name: Write host ps output
  delegate_to: localhost
  copy:
    content: "{{ ps.stdout }}"
    dest: "{{ zuul.executor.log_root }}/zuul-info/ps.{{ inventory_hostname }}.txt"
