---

- hosts: all
  roles:
    - acquire-ip-address

- hosts: deployment
  roles:
    - prepare-template-for-ansible-deployer
    - contrail-ansible-deployer

- hosts: all:!deployment
  roles:
    - contrail-ansible-deployer-debug

- hosts: deployment
  roles:
    - sanitytest
  retries: 2
  delay: 10
  until: sanity_result.rc == 0
