---
- hosts: all
  roles:
    # TODO: fix it
    # 2019-07-08 20:17:47.576396 | TASK [skip-job : find the current patchset]
    # 2019-07-08 20:17:47.651439 | builder | ERROR: Executing local code is prohibited
    #- role: skip-job
    #  vars:
    #    job_name: 'contrail-vnc-unittest-centos7-tntestr'
    - zuul-include-vars
    - contrail-unittests-tntestr
