---

# workaround for failed sandesh tests
- set_fact:
    parallel_jobs: '8'
- set_fact:
    parallel_jobs: '1'
  when: item == 'sandesh:test'

- name: 'running target {{ item }}'
  shell: "timeout 3600s bash -eo pipefail -c '{{ venv_dir}}/bin/tntestr --debug --less-strict -j {{ parallel_jobs }} {{ item }} | tee -a {{ tntestr_output }}'"
  args:
    executable: '/bin/bash'
    chdir: '{{ packaging.target_dir }}'
  become: true
  environment:
    CONTRAIL_COMPILE_WITHOUT_SYMBOLS: yes
  register: inner
  failed_when: false

- name: 'target {{ item }} failed?'
  set_fact:
    tests_failed: true
  changed_when: inner.rc != 0
  when: inner.rc != 0
