---
test_target: 'sanity'
openstack_version: 'ocata'
contrail_version: >-
  {%- if zuul.change is defined -%}
    {{ zuul.change }}-{{ zuul.patchset }}
  {%- else -%}
    {{ contrail_container_tag }}
  {%- endif -%}
contrail_docker_registry: 'localhost:5000'

