---
test_target: 'ci_sanity'
openstack_version: 'ocata'
contrail_version: >-
  {%- if zuul.change is defined -%}
    {{ zuul.change }}-{{ zuul.patchset }}
  {%- else -%}
    {{ packaging.docker_version }}
  {%- endif -%}
contrail_docker_registry: "{{ nexus.fqdn }}:{{ nexus.registry.tungsten_ci }}"

