---
control_plane_roles:
  - config_database
  - config
  - device_manager
  - control
  - analytics_database
  - analytics
  - analytics_snmp
  - analytics_alarm
  - webui
  - openstack

data_plane_roles:
  - vrouter
  - openstack_compute
