---
- name: Gather dmesg output
  command: dmesg
  register: dmesg

- name: Write host dmesg output
  delegate_to: localhost
  copy:
    content: "{{ dmesg.stdout }}"
    dest: "{{ zuul.executor.log_root }}/zuul-info/dmesg.{{ inventory_hostname }}.txt"

