---
- hosts: all
  roles:
    - acquire-ip-address
  tasks: 
    - name: Fetch helm repos to executor
      synchronize:
        src: "{{ zuul.executor.work_root }}/{{ packaging.target_dir }}/src/{{ zuul.project.canonical_name }}/Juniper/{{ item }}"
        dest: "/opt"
      with_items:
        - openstack-helm-infra
        - openstack-helm
        - contrail-helm-deployer

- hosts: deployment
  roles:
    - contrail-helm
    - prepare-template-for-helm-sanity
    - sanitytest
