---

- name: prepare config directory
  file:
    path: "{{ devenv_dir }}/config/etc"
    state: directory
    recurse: true

- name: copy repository files
  become: yes
  command: "cp -fR {{ item }} {{ devenv_dir }}/config{{ item }}"
  with_items:
    - /etc/pip.conf
    - /etc/yum.repos.d
    - /etc/yum.conf
