---

- name: Fetch build containers logs
  include: fetch_log_directory.yaml
  with_items:
    - {src: "{{ devenv_dir }}/container" , dst: "build-devenv-logs"}
    - {src: "{{ test_dir }}" , dst: "build-test-logs"}
    - {src: "{{ container_builder_dir }}/containers" , dst: "build-containers-logs"}
    - {src: "{{ deployers_builder_dir }}/containers" , dst: "build-deployers-logs"}

- name: Fetch built images
  shell: "docker images"
  become: true
  ignore_errors: True
  tags:
    - skip_ansible_lint

- name: Get ps output
  shell: "ps aux -H"
  tags:
    - skip_ansible_lint
