---
- name: set up infrastructure repositories
  include: copy-repos.yaml

- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"
    build_number: "{{ build_number | default('unset_build_number') }}"

- name: Prepare build configuration - {{ item }}.tmpl
  template:
    src: "{{ item }}.j2"
    dest: "{{ devenv_dir }}/{{ item }}.tmpl"
  with_items:
    - common.env

- name: Build containers
  shell: "./startup.sh"
  become: true
  args:
    chdir: "{{ devenv_dir }}"
  environment:
    AUTOBUILD: 1
    BUILD_DEV_ENV: 1
    BUILD_TEST_CONTAINERS: 1
    SRC_ROOT: "{{ ansible_env.HOME }}/{{ packaging.target_dir }}"
    EXTERNAL_REPOS: "{{ ansible_env.HOME }}/src"
    CANONICAL_HOSTNAME: "{{ zuul.project.canonical_hostname }}"
    REGISTRY_IP: "{{ contrail_docker_registry.split(':')[0] }}"
    REGISTRY_PORT: "{{ contrail_docker_registry.split(':')[1] }}"
