---

- name: prepare local base yum mirror repo file
  yum_repository:
    name: 'docker-ce-stable'
    description: 'docker-ce-stable'
    file: 'docker-mirror'
    baseurl: '{{ docker_mirror_url }}/repository/'
    enabled: yes
    gpgcheck: no
  become: yes

